// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8JpXDWk6l6Wg0hIIgK0UMG62IokBxUE',
    appId: '1:439344746541:web:fcd5bdcf068cf704c6a8a4',
    messagingSenderId: '439344746541',
    projectId: 'nymphette-app',
    authDomain: 'nymphette-app.firebaseapp.com',
    storageBucket: 'nymphette-app.firebasestorage.app',
    measurementId: 'G-BVT9GN3VM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJHTgns5kUbKtyctuK87CZAcygDiHObk',
    appId: '1:439344746541:android:b0fcc97b06074270c6a8a4',
    messagingSenderId: '439344746541',
    projectId: 'nymphette-app',
    storageBucket: 'nymphette-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AZ7GE_sLkjF_oiJCcSLKItuaNE1J3Fc',
    appId: '1:439344746541:ios:f1ce9064740992edc6a8a4',
    messagingSenderId: '439344746541',
    projectId: 'nymphette-app',
    storageBucket: 'nymphette-app.firebasestorage.app',
    iosBundleId: 'com.example.nymphette',
  );
}
